// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqzpwhhrhjryxugviaie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxenB3aGhyaGpyeXh1Z3ZpYWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTM1ODgsImV4cCI6MjA1ODY2OTU4OH0.G0Xt4gUmN5N7r8KJGkcBzkLBKgAk2mnhmqqMPzPKsNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);